-- $BEGIN
INSERT INTO mamba_fact_encounter_anc_card (encounter_id,
                                           client_id,
                                           encounter_date,
                                           cd4,
                                           where_,
                                           parity,
                                           gravida,
                                           art_codes,
                                           stk_given,
                                           ref_in_no,
                                           viral_load,
                                           return_date,
                                           unit_tb_no,
                                           woman_hbsag,
                                           anc_1_timimg,
                                           partners_age,
                                           risk_factors,
                                           client_number,
                                           gbv_risk_type,
                                           gestation_age,
                                           referral_type,
                                           serial_number,
                                           woa_scan_done,
                                           linkage_art_no,
                                           screened_for_tb,
                                           anc_visit_number,
                                           partner_clinic_no,
                                           who_clinical_stage,
                                           hiv_viral_load_date,
                                           partners_stk_result,
                                           emtct_risk_assesment,
                                           other_treatment_given,
                                           partner_linked_to_art,
                                           womans_initial_result,
                                           infant_arv_prophylaxis,
                                           client_has_presumptive_tb,
                                           date_cd4_sample_collected,
                                           family_planning_counseling,
                                           reason_for_next_appointment,
                                           complications_and_risk_factors,
                                           infant_and_young_child_feeding,
                                           maternal_nutrition_counselling,
                                           womans_syphilis_hep_b_results,
                                           other_reason_for_next_appointment,
                                           partners_syphilis_hep_b_results,
                                           findings_after_clinical_assessment,
                                           partners_test_for_verification_results,
                                           timing ,
                                           ipt_dose ,
                                           mother_received_free_llin ,
                                           mother_received_mebandazole_dose ,
                                           tetanus ,
                                           hepatitis_b ,
                                           covid_19 ,
                                           no_of_iron_sulphates_pills ,
                                           no_of_folic_acid_pills ,
                                           no_of_iron_and_folic_acid_combined_pills  ,
                                           no_of_micronutrient_supplements_pills )
SELECT a.encounter_id,
       a.client_id,
       a.encounter_datetime,
       cd4,
       where_,
       parity,
       gravida,
       art_codes,
       stk_given,
       ref_in_no,
       viral_load,
       return_date,
       unit_tb_no,
       woman_hbsag,
       anc_1_timimg,
       partners_age,
       risk_factors,
       client_number,
       gbv_risk_type,
       gestation_age,
       referral_type,
       serial_number,
       woa_scan_done,
       linkage_art_no,
       screened_for_tb,
       anc_visit_number,
       partner_clinic_no,
       who_clinical_stage,
       hiv_viral_load_date,
       partners_stk_result,
       emtct_risk_assesment,
       other_treatment_given,
       partner_linked_to_art,
       womans_initial_result,
       infant_arv_prophylaxis,
       client_has_presumptive_tb,
       date_cd4_sample_collected,
       family_planning_counseling,
       reason_for_next_appointment,
       complications_and_risk_factors,
       infant_and_young_child_feeding,
       maternal_nutrition_counselling,
       womans_syphilis_hep_b_results,
       other_reason_for_next_appointment,
       partners_syphilis_hep_b_results,
       findings_after_clinical_assessment,
       partners_test_for_verification_results,
       timing ,
       ipt_dose ,
       mother_received_free_llin ,
       mother_received_mebandazole_dose ,
       tetanus ,
       hepatitis_b ,
       covid_19 ,
       no_of_iron_sulphates_pills ,
       no_of_folic_acid_pills ,
       no_of_iron_and_folic_acid_combined_pills  ,
       no_of_micronutrient_supplements_pills

FROM mamba_flat_encounter_anc_register a
         left join mamba_flat_encounter_anc_register_1 b on a.encounter_id = b.encounter_id;
-- $END