-- $BEGIN
CREATE TABLE mamba_fact_arv_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT NOT NULL,
    order_id INT NOT NULL UNIQUE,
    encounter_id INT,
    regimen_concept_id INT NOT NULL,
    regimen VARCHAR(255),
    drug_inventory_id INT,
    drug_name VARCHAR(255),
    date_activated DATETIME,
    date_stopped DATETIME,
    auto_expire_date DATETIME,
    coverage_start_date DATE,
    coverage_end_date DATE,
    days_on_drugs INT,
    dose DOUBLE,
    dose_units VARCHAR(100),
    quantity DOUBLE,
    quantity_units VARCHAR(100),
    duration INT,
    duration_units VARCHAR(100),
    duration_units_concept_id INT,
    frequency VARCHAR(100),
    route VARCHAR(100),
    order_number VARCHAR(50),
    order_action VARCHAR(50),
    urgency VARCHAR(50),
    voided TINYINT DEFAULT 0,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_client_id (client_id),
    INDEX idx_date_activated (date_activated),
    INDEX idx_coverage_period (coverage_start_date, coverage_end_date),
    INDEX idx_regimen_concept_id (regimen_concept_id),
    INDEX idx_active_orders (client_id, coverage_start_date, coverage_end_date, voided)
);
-- $END