-- $BEGIN
-- ============================================================================
-- HTS Contact Tracing Fact Table - Insert Script
-- ============================================================================
-- Purpose: Inserts data from HTS Contact Tracing encounters into fact table
-- Uses: mamba_flat_encounter_hts_contact_tracing (created by Mamba ETL)
-- Note: Ensure flat table is regenerated with all columns before running:
--       DROP TABLE mamba_flat_encounter_hts_contact_tracing;
--       CALL sp_mamba_flat_encounter_table_create('mamba_flat_encounter_hts_contact_tracing');
--       CALL sp_mamba_flat_encounter_table_insert('mamba_flat_encounter_hts_contact_tracing', NULL);
-- ============================================================================
INSERT INTO mamba_fact_encounter_hts_contact_tracing (
    encounter_id,
    client_id,
    patient_id,
    encounter_date,
    hts_number,
    contact_tracing_category,
    contact_type,
    reason_why_at_risk,
    other_reason_why_at_risk,
    entry_point_hf,
    other_entry_point_hf,
    entry_point_community,
    other_entry_point_community,
    special_category,
    other_special_category,
    number_sexual_partners,
    number_biological_children,
    number_social_contact,
    number_pwid_contact,
    attempt_made,
    index_counselled,
    index_date_reached,
    encounter_outcome,
    remarks,
    contact_name,
    contact_number,
    contact_category,
    other_contact_category,
    common_name,
    contact_age,
    contact_sex,
    contact_telephone,
    contact_alternative_telephone,
    contact_residential_place,
    contact_notification_method,
    contact_violence_history,
    contact_encounter_date,
    contact_reach_attempt,
    contact_encounter_means,
    other_contact_encounter_means,
    contact_encounter_outcome,
    other_contact_encounter_outcome,
    hiv_test_date,
    hiv_test_results,
    case_closure_status,
    other_case_closure_status,
    contact_clinic_number,
    hiv_prevention_services,
    other_prevention_services,
    experienced_violence,
    type_of_violence,
    contact_care_comments
)
SELECT
    encounter_id,
    client_id,
    client_id AS patient_id,
    encounter_datetime AS encounter_date,
    hts_number,
    contact_tracing_category,
    contact_type,
    reason_why_at_risk,
    other_reason_why_at_risk,
    entry_point_hf,
    other_entry_point AS other_entry_point_hf,
    entry_point_community,
    other_community_entry_point AS other_entry_point_community,
    special_category,
    other_special_category,
    CAST(number_sexual_partners AS CHAR) AS number_sexual_partners,
    CAST(number_biological_children AS CHAR) AS number_biological_children,
    CAST(number_social_contact AS CHAR) AS number_social_contact,
    CAST(number_pwid_contact AS CHAR) AS number_pwid_contact,
    attempt_made,
    index_counselled,
    index_date_reached,
    encounter_outcome,
    remarks,
    contact_name,
    contact_number,
    contact_category,
    other_contact_category,
    common_name,
    CAST(contact_age AS CHAR) AS contact_age,
    contact_sex,
    contact_telephone,
    contact_alternative_telephone,
    contact_residential_place,
    contact_notification_method,
    contact_violence_history,
    contact_encounter_date,
    contact_reach_attempt,
    contact_encounter_means,
    other_contact_encounter_means,
    contact_encounter_outcome,
    other_contact_encounter_outcome,
    hiv_test_date,
    hiv_test_results,
    case_closure_status,
    other_case_closure_status,
    contact_clinic_number,
    hiv_prevention_services,
    other_prevention_services,
    experienced_violence,
    type_of_violence,
    contact_care_comments
FROM mamba_flat_encounter_hts_contact_tracing;
-- $END
