-- $BEGIN
INSERT INTO mamba_fact_encounter_cacx_screening (encounter_id,
                                               client_id,
                                               patient_id,
                                               encounter_date,
                                               serial_number,
                                               reg_number,
                                               referred_in,
                                               entry_point,
                                               hiv_status,
                                               art_status,
                                               ever_been_screened,
                                               given_pre_test,
                                               menstruating_now,
                                               pregnant_now,
                                               been_pregnant_last_three_months,
                                               hysterectomy,
                                               previously_on_cacx_treatment,
                                               cacx_screening,
                                               ready_to_receive_service)
SELECT a.encounter_id,
       a.client_id,
       a.client_id AS patient_id,
       a.encounter_datetime,
       serial_number,
       reg_number,
       referred_in,
       entry_point,
       hiv_status,
       art_status,
       ever_been_screened,
       given_pre_test,
       menstruating_now,
       pregnant_now,
       been_pregnant_last_three_months,
       hysterectomy,
       previously_on_cacx_treatment,
       cacx_screening,
       ready_to_receive_service
FROM mamba_flat_encounter_cacx_screening a;
-- $END