-- $BEGIN
INSERT INTO mamba_fact_encounter_vl_request (encounter_id,
                                            client_id,
                                            encounter_date,
                                            indication_for_vl_testing,
                                            sample_collection_date,
                                            art_start_date,
                                            current_who_clinical_stage,
                                            current_regimen_line,
                                            current_regimen,
                                            other_current_regimen,
                                            pregnant_mother,
                                            anc_number,
                                            pnc_number,
                                            breastfeeding_mother,
                                            has_active_tb,
                                            tb_treatment_phase,
                                            arv_adherence,
                                            dsdm_models,
                                            viral_load_qualitative,
                                            viral_load_quantitative)
SELECT a.encounter_id,
       a.client_id,
       a.encounter_datetime,
       indication_for_vl_testing,
       sample_collection_date,
       art_start_date,
       current_who_clinical_stage,
       current_regimen_line,
       current_regimen,
       other_current_regimen,
       pregnant_mother,
       anc_number,
       pnc_number,
       breastfeeding_mother,
       has_active_tb,
       tb_treatment_phase,
       arv_adherence,
       dsdm_models,
       viral_load_qualitative,
       viral_load_quantitative
FROM mamba_flat_encounter_vl_request a
WHERE a.voided = 0;
-- $END